import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PageHero } from "@/components/PageHero";
import { SectionHeading } from "@/components/SectionHeading";
import { makePageMetadata } from "@/lib/metadata";
import { isLocale } from "@/lib/site";

const title = { en: "Family resources", ku: "سەرچاوەی خێزان" };
const description = { en: "Trusted information and practical guidance for families of people with Down syndrome and intellectual disabilities.", ku: "زانیاریی باوەڕپێکراو و ڕێنماییی کرداری بۆ خێزانەکانی کەسانی خاوەن سندرۆمی داون و کەمتواناییی هزری." };
export function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { return makePageMetadata(params, title, description, "/resources"); }

export default async function ResourcesPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: raw } = await params; if (!isLocale(raw)) notFound(); const isKu = raw === "ku";
  return <>
    <PageHero eyebrow={isKu ? "بۆ خێزانەکان" : "For families"} title={isKu ? "زانیاریی ڕوون. ڕێنمایی بە ڕێزەوە." : <>Clear information.<br /><em>Respectful guidance.</em></>} intro={<p>{isKu ? "لێرە سەرچاوەی باوەڕپێکراو و ڕێنماییی لەسەر بنەمای ماف بۆ خێزان و پشتیوانان کۆکراوەتەوە." : "This hub brings together trusted reference points and rights-based guidance for families and supporters."}</p>} aside={<p>{isKu ? "زانیاریی ئەم ماڵپەڕە گشتییە و جێگرەوەی ڕاوێژی تایبەتیی پزیشکی، یاسایی یان پەروەردەیی نییە." : "Website information is general and does not replace individual medical, legal or educational advice."}</p>} />
    <section className="section-pad"><div className="shell"><SectionHeading eyebrow={isKu ? "سەرچاوەی بەردەست" : "Available now"} title={isKu ? "سەرچاوە جیهانییە باوەڕپێکراوەکان لە یەک شوێندا." : "Trusted global references in one place."} /><div className="resource-grid"><a href="https://www.un.org/development/desa/disabilities/convention-on-the-rights-of-persons-with-disabilities.html" target="_blank" rel="noreferrer"><span>{isKu ? "ماف" : "Rights"}</span><h3>{isKu ? "ڕێککەوتننامەی نەتەوە یەکگرتووەکان بۆ مافی کەسانی خاوەن کەمتوانایی" : "UN Convention on the Rights of Persons with Disabilities"}</h3><p>{isKu ? "بنەمای نێودەوڵەتی بۆ شکۆ، بەشداری، گشتگیری و دەستگەیشتن." : "The international rights framework for dignity, participation, inclusion and access."}</p><b>↗</b></a><a href="https://www.unicef.org/unicef-disability-inclusion-policy-and-strategy-dipas-2022-2030" target="_blank" rel="noreferrer"><span>{isKu ? "گشتگیری" : "Inclusion"}</span><h3>{isKu ? "سیاسەت و ستراتیژیی گشتگیریی کەمتواناییی یونیسێف" : "UNICEF Disability Inclusion Policy and Strategy"}</h3><p>{isKu ? "ڕێنمایی بۆ دروستکردنی کۆمەڵگایەکی بێ کۆسپ و گشتگیر بۆ هەموو منداڵان." : "A framework for barrier-free, inclusive communities for every child."}</p><b>↗</b></a><a href="https://www.unicef.org/documents/global-report-children-developmental-disabilities" target="_blank" rel="noreferrer"><span>{isKu ? "توێژینەوە" : "Evidence"}</span><h3>{isKu ? "ڕاپۆرتی جیهانی لەسەر منداڵانی خاوەن کەمتواناییی گەشەیی" : "Global report on children with developmental disabilities"}</h3><p>{isKu ? "ڕاپۆرتێکی هاوبەشی ڕێکخراوی تەندروستیی جیهانی و یونیسێف بۆ گشتگیری و یەکسانیی تەندروستی." : "A joint WHO–UNICEF call for inclusion and health equity."}</p><b>↗</b></a></div></div></section>
    <section className="resource-roadmap section-pad section-sand"><div className="shell"><SectionHeading eyebrow={isKu ? "ڕێنماییی کرداری" : "Practical guidance"} title={isKu ? "لە پرسیاری دروستەوە دەست پێبکە." : "Start with the right questions."} /><div className="roadmap-list">{[
      [isKu ? "لە کاتی دۆزینەوەی پسپۆڕ" : "When choosing a professional", isKu ? "لە شایستەیی، ئەزموون، شێوازی پەیوەندی و چۆنیەتی بەشداریی خێزان بپرسە." : "Ask about qualifications, experience, communication and how families take part."],
      [isKu ? "لە کاتی گفتوگۆ لەگەڵ قوتابخانە" : "When speaking with a school", isKu ? "لە تواناکان، پێداویستیی فێربوون و چۆنیەتی بەشداریی ناو پۆل دەست پێبکە." : "Begin with strengths, learning needs and meaningful classroom participation."],
      [isKu ? "لە کاتی خوێندنەوەی زانیاری" : "When reading information", isKu ? "سەرچاوە، بەروار، بەڵگە و ئەوەی کێ پێداچوونەوەی بۆ کردووە بپشکنە." : "Check the source, date, evidence and who reviewed the information."],
      [isKu ? "لە کاتی باسکردنی سندرۆمی داون" : "When talking about Down syndrome", isKu ? "سەرەتا کەسەکە ببینە، نەک ناوی سندرۆمەکە؛ هەمیشە زمانێکی بەڕێز بەکاربهێنە." : "See the person before the diagnosis and use respectful, individual language."],
    ].map(([h,p],i) => <article key={h}><span>0{i+1}</span><div><h3>{h}</h3><p>{p}</p></div></article>)}</div></div></section>
    <section className="resource-disclaimer"><div className="shell"><strong>{isKu ? "تێبینی گرنگ" : "Important note"}</strong><p>{isKu ? "زانیاری ئەم ماڵپەڕە گشتییە و جێگرەوەی ڕاوێژی پزیشکی، یاسایی یان پەروەردەیی تاکەکەسی نییە. بۆ دۆخی فریاکەوتن پەیوەندی بە خزمەتگوزاری فریاکەوتنی ناوخۆ بکە." : "Information on this site is general and is not a substitute for individual medical, legal or educational advice. In an emergency, contact the appropriate local emergency service."}</p></div></section>
  </>;
}
